version: "3.8"

services:

  consumer:
    build:
      context: ../..
      dockerfile: transfer/transfer-04-open-telemetry/open-telemetry-consumer/Dockerfile
    volumes:
      - ./:/resources
    ports:
      - "9191:9191"
      - "9192:9192"
    environment:
      EDC_HOSTNAME: consumer
      OTEL_SERVICE_NAME: consumer
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_METRICS_EXPORTER: prometheus
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 9292
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_CONTROL_PORT: 9193
      WEB_HTTP_CONTROL_PATH: /control
      EDC_CONTROL_ENDPOINT: http://consumer:9193/control
      EDC_DSP_CALLBACK_ADDRESS: http://consumer:9292/protocol
      EDC_PARTICIPANT_ID: consumer
      EDC_API_AUTH_KEY: password
    entrypoint: java
      -javaagent:/app/libs/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/resources/logging.properties
      -jar /app/connector.jar

  provider:
    build:
      context: ../..
      dockerfile: transfer/transfer-04-open-telemetry/open-telemetry-provider/Dockerfile
    volumes:
      - ./:/resources
    ports:
      - "8181:8181"
      - "8182:8182"
    environment:
      EDC_HOSTNAME: provider
      OTEL_SERVICE_NAME: provider
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      WEB_HTTP_PORT: 8181
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 8182
      WEB_HTTP_MANAGEMENT_PATH: /management
      WEB_HTTP_PROTOCOL_PORT: 8282
      WEB_HTTP_PROTOCOL_PATH: /protocol
      WEB_HTTP_CONTROL_PORT: 8183
      WEB_HTTP_CONTROL_PATH: /control
      EDC_CONTROL_ENDPOINT: http://provider:8183/control
      EDC_DSP_CALLBACK_ADDRESS: http://provider:8282/protocol
      EDC_PARTICIPANT_ID: provider
      EDC_SAMPLES_TRANSFER_01_ASSET_PATH: /resources/README.md
    entrypoint: java
      -javaagent:/app/libs/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/resources/logging.properties
      -jar /app/connector.jar

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
